export interface ApiResponse<T = any> {
  data: T | null;
  error: string | null;
  details?: string | null;
  ok: boolean;
  isStarting?: boolean;
  rateLimited?: boolean;
}

export const safeFetchJson = async <T = any>(res: Response): Promise<ApiResponse<T>> => {
  try {
    const text = await res.text();
    if (!text) {
      if (res.status === 403)
        return {
          data: null,
          error: "Access denied. Insufficient permissions for this role.",
          ok: false,
        };
      return { data: null, error: null, ok: res.ok };
    }

    // Check for platform warmup/system messages
    if (
      text.includes("<title>Starting Server...</title>") ||
      text.includes("Please wait while your application starts...")
    ) {
      return {
        data: null,
        error: "Application is starting. Please wait...",
        ok: false,
        isStarting: true,
      };
    }

    if (text.includes("Rate exceeded") || text.includes("RESOURCE_EXHAUSTED")) {
      return {
        data: null,
        error: "Rate limit exceeded. Please wait.",
        ok: false,
        rateLimited: true,
      };
    }

    if (!res.ok) {
      try {
        const data = JSON.parse(text);
        if (res.status === 401) {
          const hasLocalSession = typeof window !== "undefined" && !!localStorage.getItem("erp_user");
          if (!hasLocalSession) {
            window.dispatchEvent(new CustomEvent("api:unauthorized"));
          }
        }
        return {
          data: null,
          error: data.error || data.message || `Error ${res.status}`,
          details: data.details || null,
          ok: false,
        };
      } catch (err) {
        // Fallback for HTML/Text responses generated by Nginx/Proxy
        if (res.status === 403)
          return {
            data: null,
            error: "Access denied. Insufficient permissions for this role.",
            ok: false,
          };
        if (res.status === 401) {
          const hasLocalSession = typeof window !== "undefined" && !!localStorage.getItem("erp_user");
          if (!hasLocalSession) {
            window.dispatchEvent(new CustomEvent("api:unauthorized"));
          }
          return { data: null, error: "Unauthorized access", ok: false };
        }
        if (res.status === 404)
          return { data: null, error: "Resource not found", ok: false };
        if (res.status >= 500)
          return {
            data: null,
            error: `Internal server error (${res.status})`,
            ok: false,
          };

        return {
          data: null,
          error: `Protocol error (${res.status})`,
          ok: false,
        };
      }
    }

    // if res.ok is true
    try {
      const data = JSON.parse(text);
      return { data, error: null, ok: true };
    } catch (e) {
      console.warn("API succeeded but response is not JSON. URL:", res.url);
      return { data: text as any, error: null, ok: true };
    }
  } catch (err) {
    return { data: null, error: "Internal communication error", ok: false };
  }
};

let cachedUserEmail: string | null = null;
let lastStorageCheck = 0;

function getCachedUserEmail(): string | null {
  if (typeof window === "undefined") return null;
  try {
    const stored = localStorage.getItem("erp_user");
    if (stored) {
      const u = JSON.parse(stored);
      return u?.username || null;
    }
  } catch (e) {
    return null;
  }
  return null;
}

function getCachedAuthToken(): string | null {
  if (typeof window === "undefined") return null;
  try {
    return localStorage.getItem("erp_token") || null;
  } catch (e) {
    return null;
  }
}

if (typeof window !== "undefined") {
  window.addEventListener("storage", (e) => {
    if (e.key === "erp_user" || e.key === "erp_token") {
      lastStorageCheck = 0;
    }
  });
}

export interface ApiFetchOptions extends Omit<RequestInit, "body"> {
  /**
   * Body boleh berupa BodyInit standar (FormData, Blob, string, dst.)
   * maupun objek/array biasa — objek akan di-JSON.stringify otomatis.
   */
  body?: BodyInit | Record<string, any> | any[] | null;
}

export const apiFetch = async <T = any>(
  url: string,
  options: ApiFetchOptions = {},
  userEmail: string = "",
  retries = 1,
  isStartingRetries = 10,
  rateLimitRetries = 4,
  currentBackoffMs = 1500
): Promise<ApiResponse<T>> => {
  let effectiveEmail = userEmail || getCachedUserEmail();
  const authToken = getCachedAuthToken();

  let body: BodyInit | null | undefined = options.body as BodyInit | null | undefined;
  if (
    options.body &&
    typeof options.body === "object" &&
    !(options.body instanceof FormData) &&
    !(options.body instanceof Blob) &&
    !(options.body instanceof ArrayBuffer) &&
    !(options.body instanceof URLSearchParams) &&
    !ArrayBuffer.isView(options.body) &&
    !(options.body instanceof ReadableStream) &&
    typeof options.body !== "string"
  ) {
    try {
      body = JSON.stringify(options.body);
    } catch (e) {
      console.error("Failed to stringify request body", e);
    }
  }

  const headers = {
    ...(body instanceof FormData
      ? {}
      : { "Content-Type": "application/json" }),
    ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
    ...(effectiveEmail ? { "x-user-email": effectiveEmail } : {}),
    ...(options.headers || {}),
  } as Record<string, string>;

  // Only GET requests should be retried automatically for idempotency safety on generic network errors
  const shouldRetry =
    retries > 0 && (!options.method || options.method.toUpperCase() === "GET");

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15000); // 15 second timeout

  try {
    const res = await fetch(url, {
      ...options,
      body,
      headers,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    const parsedRes = await safeFetchJson(res);

    // Exponential Backoff for Rate Limits (429 or RESOURCE_EXHAUSTED)
    if ((parsedRes.rateLimited || res.status === 429) && rateLimitRetries > 0) {
      console.warn(`[Rate Limit] API ${url} throttled. Retrying in ${currentBackoffMs}ms... (${rateLimitRetries} retries left)`);
      await new Promise((resolve) => setTimeout(resolve, currentBackoffMs));
      return apiFetch(url, options, userEmail, retries, isStartingRetries, rateLimitRetries - 1, currentBackoffMs * 2);
    }

    // Automatically poll if the server is starting up
    if (parsedRes.isStarting && isStartingRetries > 0) {
      console.warn(
        `Server is starting. Retrying fetch to ${url}... (${isStartingRetries} retries left)`,
      );
      await new Promise((resolve) => setTimeout(resolve, 3000)); // wait 3 seconds
      return apiFetch(url, options, userEmail, retries, isStartingRetries - 1, rateLimitRetries, currentBackoffMs);
    }

    return parsedRes;
  } catch (err: any) {
    clearTimeout(timeoutId);
    if (err.name === "AbortError") {
      return {
        data: null,
        error: "Request timed out. Please try again.",
        ok: false,
      };
    }
    if (shouldRetry) {
      console.warn(`Retrying fetch to ${url}...`);
      await new Promise((resolve) => setTimeout(resolve, 500)); // wait 500ms before retry
      return apiFetch(url, options, userEmail, retries - 1, isStartingRetries, rateLimitRetries, currentBackoffMs);
    }
    return {
      data: null,
      error: "Network error. Check your connection.",
      ok: false,
    };
  }
};
